Fix panic caused by accessing non-existent header
We encountered a panic while checking out a repository with many LFS
files, even with a fresh build from main:

	panic: runtime error: index out of range [0] with length 0

	goroutine 49 [running]:
	github.com/git-lfs/git-lfs/v3/tq.(*basicDownloadAdapter).download(0xc0000148d0, 0xc0009391a0, 0xc0005e7970, 0x0, 0xc000014620, 0x0, {0xb4d7b0, 0xc000552780})
		/data00/go/pkg/mod/github.com/git-lfs/git-lfs/v3@v3.4.0/tq/basic_download.go:156 +0x14a8
	github.com/git-lfs/git-lfs/v3/tq.(*basicDownloadAdapter).DoTransfer(0xc0000148d0, {0x40?, 0x0?}, 0xc0009391a0, 0x0?, 0x0?)
		/data00/go/pkg/mod/github.com/git-lfs/git-lfs/v3@v3.4.0/tq/basic_download.go:96 +0x3a8
	github.com/git-lfs/git-lfs/v3/tq.(*adapterBase).worker(0xc0000c46c0, 0x5, {0x0, 0x0})
		/data00/go/pkg/mod/github.com/git-lfs/git-lfs/v3@v3.4.0/tq/adapterbase.go:183 +0x58b
	created by github.com/git-lfs/git-lfs/v3/tq.(*adapterBase).Begin
		/data00/go/pkg/mod/github.com/git-lfs/git-lfs/v3@v3.4.0/tq/adapterbase.go:96 +0x270
	error: external filter 'git-lfs filter-process' failed

After some digging, we found the panic was caused by accessing a
non-existent "Retry-After" response header when receiving a 429 status
code. We should use the `Get()` method to safely access response
headers.

Reported-by: Yunpeng Li <liyunpeng.chn@bytedance.com>
Signed-off-by: Xing Xin <xingxin.xx@bytedance.com>